/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlightMarkupRouteImport } from './routes/flight-markup'
import { Route as IndexRouteImport } from './routes/index'

const FlightMarkupRoute = FlightMarkupRouteImport.update({
  id: '/flight-markup',
  path: '/flight-markup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flight-markup': typeof FlightMarkupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flight-markup': typeof FlightMarkupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flight-markup': typeof FlightMarkupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flight-markup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flight-markup'
  id: '__root__' | '/' | '/flight-markup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightMarkupRoute: typeof FlightMarkupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flight-markup': {
      id: '/flight-markup'
      path: '/flight-markup'
      fullPath: '/flight-markup'
      preLoaderRoute: typeof FlightMarkupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightMarkupRoute: FlightMarkupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
